### ISSUE TITLE
Add a Contributing.md

### ISSUE THREAD

**Issue by emem365** [emem365/news_app#17]
Add a Contributing.md file for new contributors to follow
Also link this up in Readme

**Comment by Kunal1198** [comment]
Hi @emem365 Can I work on this?

**Comment by emem365** [comment]
@Kunal1198 Sure Go ahead🚀

**Comment by LondonTran** [comment]
I submitted a pull request for this :)
I created CONTRIBUTING.md file and also linked it at the bottom of README.md

**Comment by emem365** [comment]
Tough luck @Kunal1198 . I merged this PR by @LondonTran . Maybe you could work on something else. Good Luck

**Comment by Kunal1198** [comment]
Hi @emem365 How can you merge without even assigning to @LondonTran ?

**Comment by LondonTran** [comment]
I noticed that no one was assigned so I worked on the pull request.
